name: setup_python_env
description: Setup Python environment
runs:
  using: composite
  steps:
  - name: Install Python dependencies
    run: |-
      pip install git+https://github.com/kedro-org/kedro@main
      pip install wheel
      pip install toposort
      pip install -r package/test_requirements.txt -r demo-project/src/docker_requirements.txt -U
    shell: bash
  - name: Echo package versions
    run: |-
      python -V
      pip freeze
    shell: bash