name: setup_cypress_requirements
description: Setup Cypress requirements
runs:
  using: composite
  steps:
  - name: Install cypress system dependencies
    run: |-
      sudo sed -i 's/archive.ubuntu.com/us-east-1.ec2.archive.ubuntu.com/g' /etc/apt/sources.list
      sudo apt-get update
      sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    shell: bash