name: win_setup_python_env
description: GitHub Action to setup Python environment on Windows
inputs:
  python_version:
    description: Python version to use for the environment
    required: false
runs:
  using: composite
  steps:
  - name: Install and initialize Miniconda
    uses: conda-incubator/setup-miniconda@v2
    with:
      auto-update-conda: true
      python-version: ${{ inputs.python_version }}
  # - name: Explicitly initialize conda
  #   run: conda init bash
  #   shell: bash      
  - name: Create 'kedro-viz' conda environment
    run: conda create --name kedro-viz python=${{ inputs.python_version }} -y
    shell: pwsh
  - name: Install Kedro-Viz dependencies
    run: |-
      conda init pwsh
      conda activate kedro-viz
      pip install git+https://github.com/kedro-org/kedro@main
      pip install -r package/test_requirements.txt -U
    shell: pwsh
  - name: Echo package versions
    run: |-
      conda activate kedro-viz
      python -V
      pip freeze
    shell: pwsh
  - name: Setup MSYS2 and install 'make' command
    uses: msys2/setup-msys2@v2
    with:
      update: true
      install: make