name: win_setup_python_env
description: GitHub Action to setup Python environment on Windows
inputs:
  python_version:
    description: Python version to use for the environment
    required: false
runs:
  using: composite
  steps:
  - name: Setup Python
    uses: actions/setup-python@v2
    with:
      python-version: ${{ inputs.python_version }}
  - name: Create 'kedro-viz' conda environment
    run: conda create --name kedro-viz python=${{ inputs.python_version }} -y
    shell: bash
  - name: Install Kedro-Viz dependencies
    run: |-
      conda activate kedro-viz
      pip install git+https://github.com/kedro-org/kedro@main
      pip install -r package/test_requirements.txt -U
    shell: bash
  - name: Echo package versions
    run: |-
      conda activate kedro-viz
      python -V
      pip freeze
    shell: bash
  - name: Setup MSYS2 and install 'make' command
    uses: msys2/setup-msys2@v2
    with:
      update: true
      install: make