name: Setup Node.js and Install Dependencies
description: Sets up a specific Node.js version, caches Node modules, and installs Node dependencies.

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '16.13.2'

  package-path:
    description: 'Path to package.json file'
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{ inputs.node-version }}

    - id: npm-cache-dir
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      with:
        path: "${{ steps.npm-cache-dir.outputs.dir }}"
        key: "${{ runner.os }}-node-${{ hashFiles(inputs.package-path + '/package-lock.json') }}"
        restore-keys: "${{ runner.os }}-node-"

    - run: npm ci
      shell: bash
