name: win_setup
description: This is a GitHub Action for setting up a Windows environment.
inputs:
  python_version:
    description: The version of Python to use.
    required: false
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4.1.0
  - uses: "./.github/actions/win_setup_python_env"
    with:
      python_version: "${{ inputs.python_version }}"
  - uses: "./.github/actions/nvm_use_npm_install"
  - uses: "./.github/actions/npm_build"