name: nvm_use_npm_install
description: GitHub Action to use NVM and install Node dependencies
runs:
  using: composite
  steps:
  - name: Setup Node.js environment
    uses: actions/setup-node@v2
    with:
      node-version: '16.13.2'
  - name: Install Node dependencies
    run: |-
      node -v
      npm install
    shell: pwsh