name: Blocking Issues
# Prevents PR merges if 'blocking' issues are open 
# when an issue is closed or a PR is opened/edited.

on:
  issues:
    types: [closed]
  pull_request_target:
    types: [opened, edited]

jobs:
  blocking_issues:
    runs-on: ubuntu-latest
    name: Checks for blocking issues

    steps:
      - uses: Levi-Lesches/blocking-issues@v1.1
