name: Build frontend
on:
  push:
    paths-ignore:
      - 'package/**'
  pull_request:
    paths-ignore:
      - 'package/**'
  workflow_dispatch:
jobs:
  javascript_lint_and_tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.9" ]
    uses: ./.github/workflows/javascript-lint-and-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}   