name: Build frontend
# Runs JavaScript linting & tests on the frontend code for Ubuntu OS and Python 3.9.

on:
  push:
    paths-ignore:
      - 'package/**'
  pull_request:
    paths-ignore:
      - 'package/**'
  workflow_dispatch:
jobs:
  javascript_lint_and_tests:
    uses: ./.github/workflows/javascript-lint-and-tests.yml