name: kedro-org/kedro-viz/deploy_demo
on:
  workflow_dispatch:
    inputs:
      backend_change:
        required: true
      ci_change:
        required: true
      frontend_change:
        required: true
env:
  AWS_REGION: xxxxst-2
  CACHE_VERSION: xxxx
  NPM_TOKEN: xxxx5775
  SNYK_TOKEN: xxxxa727
  TWINE_NON_INTERACTIVE: xxxx
  TWINE_PASSWORD: xxxxi3Xc
  TWINE_REPOSITORY_URL: xxxxacy/
  TWINE_USERNAME: xxxxen__
jobs:
  deploy_demo:
    if: github.ref == 'refs/heads/demo'
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.9-node
    env:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    steps:
    - uses: actions/checkout@v4.1.0
#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
    - name: Setup environment
      run: |-
        cd demo-project
        echo "AWS_ECR_URL=public.ecr.aws/g0x0s3o2/kedro-viz-live-demo" >> $BASH_ENV
        echo "KEDRO_VIZ_VERSION=$(cat .version)" >> $BASH_ENV
        echo "cd demo-project" >> $BASH_ENV
    - name: Install AWS CLI
      run: pip3 install awscli
    - name: Build demo container image
      run: |-
        echo "kedro_viz==$KEDRO_VIZ_VERSION" >> src/docker_requirements.txt
        docker build -t $AWS_ECR_URL:$KEDRO_VIZ_VERSION .
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
        docker push $AWS_ECR_URL:$KEDRO_VIZ_VERSION
    - name: Create a new lightsail deployment
      run: |-
        # install lightsail cli
        # run https://docs.aws.amazon.com/cli/latest/reference/lightsail/create-container-service-deployment.html#create-container-service-deployment
        aws lightsail create-container-service-deployment --region eu-west-2 --cli-input-json file://./lightsail.json
