name: Run e2e tests on Kedro-Viz
# Runs end-to-end tests on Kedro-Viz for different 
# operating systems and Python versions.

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
jobs:
    e2e_tests:
        runs-on: ${{ inputs.os }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v4


        - name: Print ref
          env:
            ONLY_REF: ${{ github.ref }}
          run: "echo 'Base ref: $ONLY_REF'"

        - name: Print base ref
          env:
            BASE_REF_ONLY: ${{ github.base.ref }}
          run: "echo 'Base ref: $BASE_REF_ONLY'"

        - name: Print event base ref
          env:
            EVENT_BASE_REF: ${{ github.event.pull_request.base.ref }}
          run: "echo 'Base ref: $EVENT_BASE_REF'"

        - name: Setup Tests
          uses: "./.github/actions/setup_tests"
          with:
            os: ${{ inputs.os }}
            python-version: ${{ inputs.python-version }}
            
        - name: Run all end to end tests
          run: make e2e-tests 