name: Run unit-tests on Kedro-Viz
# Runs unit tests on Kedro-Viz across different 
# OS and Python versions after environment setup.

on:
  workflow_call:
    inputs:
      os:
        type: string
      python-version:
        type: string
jobs:
    unit_tests:
        runs-on: ${{ inputs.os }}

        # below condition checks if the operating system is Ubuntu, or 
        # Run on Windows and
        # main/demo branch or 
        # pull request to main with Python 3.10
        if: >
          inputs.os == 'ubuntu-latest' || 
          (
            (
              github.ref == 'refs/heads/main' || 
              github.ref == 'refs/heads/demo' || 
              (
                github.event.pull_request.base.ref == 'main' && 
                inputs.python-version == '3.10'
              )
            ) && 
            inputs.os == 'windows-latest'
          )
          
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Tests
          uses: "./.github/actions/setup_tests"
          with:
            os: ${{ inputs.os }}
            python-version: ${{ inputs.python-version }}
            
        - name: Run Python tests
          run: make pytest      